-- CREATE TABLE CATS2(
	-- NAME VARCHAR(50) NOT NULL,
    -- AGE INT NOT NULL );
    
-- DESC CATS2;
-- INSERT INTO CATS2 (NAME,AGE) VALUES ('HONEY',4);
-- INSERT INTO CATS2 (NAME,AGE) VALUES ('DARLING',7),('LILY',5);
INSERT INTO CATS2 (NAME,AGE) VALUES ('ROSE\'S CAT',2);

SELECT * FROM CATS2;