-- SHOW DATABASES;

-- USE PETSHOP;

-- CREATE TABLE CATS(
-- 	NAME VARCHAR(50),
 --    AGE int
 --    ); 
-- SHOW COLUMNS FROM CATS;
-- DROP TABLE CATS;

-- CREATE TABLE PASTRIES(
	-- NAME VARCHAR(50),
    -- QUANTITY int);
-- SHOW TABLES;
-- SHOW COLUMNS FROM PASTRIES; 
-- DESC PASTRIES;
-- DROP TABLE PASTRIES;

-- use petshop;
-- DROP TABLE DOGS;
-- CREATE TABLE CATS (
	-- NAME VARCHAR(50),
    -- AGE INT);
-- INSERT INTO CATS (NAME,AGE) VALUES ('ZUMBA',4);
-- INSERT INTO CATS (NAME,AGE) VALUES ('MAGGI',6);
-- INSERT INTO CATS (NAME,AGE) VALUES ('COCO',2);
-- INSERT INTO CATS (NAME,AGE) VALUES ('BLUE',5);
-- INSERT INTO CATS (NAME,AGE) VALUES ('BETH',2);
-- INSERT INTO CATS (NAME,AGE) VALUES ('TURKEY',10);

-- SELECT * FROM CATS;

-- MULTIPLE INSERT
-- INSERT INTO CATS (NAME,AGE) VALUES ('CHARLIE',10),('SADIE',3),('LAZY BEAR',1);
-- SELECT * FROM CATS;