-- "PRIMARY KEY"
-- CREATE TABLE UNIQUE_CATS(
	-- ID INT PRIMARY KEY,
    -- NAME VARCHAR(50),
    -- AGE INT);

-- INSERT INTO UNIQUE_CATS (ID,NAME,AGE)
	-- VALUES(1,'BINGO',3),(2,'SAMA',8),(45,'DEGGU',4);
    
-- SELECT * FROM unique_cats;
-- DROP TABLE UNIQUE_CATS;


-- "AUTO_INCREMENT"
 -- CREATE TABLE UNIQUE_CATS(
	-- ID INT AUTO_INCREMENT PRIMARY KEY,
   -- NAME VARCHAR(50),
    -- AGE INT);

-- desc UNIQUE_CATS;

-- INSERT INTO unique_cats (NAME,AGE)
	-- VALUES ('SAMS',6),('BINGO',8),('VIOLET',2);
    
--    SELECT * FROM unique_cats;