-- CREATE TABLE PEOPLE(
	-- FIRST_NAME VARCHAR(20),
    -- LAST_NAME VARCHAR(20),
    -- AGE INT );
    
-- INSERT INTO PEOPLE (FIRST_NAME,LAST_NAME,AGE) VALUES ('TINA','BELCHER',13);
-- INSERT INTO PEOPLE (FIRST_NAME,LAST_NAME,AGE) VALUES ('BOB','BELCHER',42);

-- SELECT *  FROM PEOPLE;

-- INSERT INTO PEOPLE (FIRST_NAME,LAST_NAME,AGE) VALUES ('LINDA','BELCHER',45),('PHILLIP','FROND',38),('CALVIN','FISCHOEDER',70);

-- DROP TABLE PEOPLE;
SHOW TABLES;